[package]
name = "doc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "1.4.1"
http-body-util = "0.1.2"
bytes = "1.6.1"
anyhow = "1.0.86"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"